site_name: Containerized Security Toolkit
site_url: https://tanishq.page/containerized-security-toolkit/home
repo_name: tanq16/containerized-security-toolkit
repo_url: https://github.com/tanq16/containerized-security-toolkit

theme:
  name: material
  logo: assets/CST-Logo.png
  favicon: assets/CST-Logo.png
  icon:
    repo: fontawesome/brands/github
  
  # Color scheme settings
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Enable useful features
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# Extra customization
extra:
  social:
    - icon: fontawesome/solid/user
      link: https://tanishq.page
      name: Personal Website
    - icon: fontawesome/brands/github
      link: https://github.com/tanq16
      name: GitHub Profile

# Navigation structure  
nav:
  - Home:
    - Overview: home/index.md
    - Getting Started: home/getting-started.md
    - Conventions: home/conventions.md
    - Contributing: home/contributing.md
  - Image Variants:
    - Overview: variants/index.md
    - General: variants/general.md
    - Cloud: variants/cloud.md
    - Dev: variants/dev.md
    - NetSec: variants/netsec.md
    - Rice: variants/rice.md
  - Tools List:
    - General: tools/general-tools.md
    - Cloud: tools/cloud-tools.md
    - Rice: tools/rice-tools.md
  - Advanced:
    - Shell Shortcuts: advanced/shortcuts.md
    - SSH & TMUX: advanced/ssh-tmux.md
    - DIY Build: advanced/build.md

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
