name: Docker Image Apple Silicon Build CI

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 7,22 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tanq16
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Build and push work docker
        uses: docker/build-push-action@v2
        with:
          context: work_docker
          file: work_docker/Dockerfile.AppleSilicon
          platforms: linux/arm64
          push: true
          tags: tanq16/sec_docker:work_apple
      
      - name: Build and push dev docker
        uses: docker/build-push-action@v2
        with:
          context: dev_docker
          file: dev_docker/Dockerfile.AppleSilicon
          platforms: linux/arm64
          push: true
          tags: tanq16/sec_docker:dev_apple
      
      - name: Build and push security docker
        uses: docker/build-push-action@v2
        with:
          context: security_docker
          file: security_docker/Dockerfile.AppleSilicon
          platforms: linux/arm64
          push: true
          tags: tanq16/sec_docker:main_apple
